name: Build Site

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  

      - name: Instalar dependências
        run: npm install

      - name: Rodar o build
        run: CI=false npm run build  # Adicionando CI=false para ignorar warnings
