name: Deploy Site

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  # Usamos o Ubuntu como ambiente de execução

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Aqui você instala a versão do Node.js que seu projeto utiliza

      - name: Instalar dependências
        run: npm install  # Instalando as dependências do seu projeto

      - name: Rodar o deploy
        run: npm run deploy  # Executando o comando npm run deploy
